---

name: Deploy to AUR

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Nightly Build"]
    types: [completed]
  workflow_dispatch:

jobs:
  deployaur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release URL
        id: getrurl
        uses: 2moe/get-releases-url-action@v0
        with:
          include: nightly
          tag: latest

      - name: Get Release Name
        id: getrname
        uses: fangqiuming/latest-release-version@v1.1.1
        with:
          property: tag_name

      - name: Clone AUR Repo
        run: |
          echo "${{ secrets.AUR_SSHKEY }}" > .ssh_key
          chown runner .ssh_key
          chmod 600 .ssh_key
          GIT_SSH_COMMAND="ssh -i ./.ssh_key -o StrictHostKeyChecking=no" git clone ssh://aur@aur.archlinux.org/libeventemitter-nightly.git /home/runner/eeaur

      - name: Update PKGBUILD and .SRCINFO
        working-directory: /home/runner/eeaur
        run: |
          cat PKGBUILD.in | sed -e "s#@VERSION@#${{ steps.getrname.outputs.version }}#g" -e "s#@URL@#${{ steps.getrurl.outputs.url }}#g" > PKGBUILD
          cat .SRCINFO.in | sed -e "s#@VERSION@#${{ steps.getrname.outputs.version }}#g" -e "s#@URL@#${{ steps.getrurl.outputs.url }}#g" > .SRCINFO

      - name: Push
        working-directory: /home/runner/eeaur
        run: |
          git add .
          git config --global user.name "Twinkle[bot]"
          git config --global user.email "example@example.com"
          git commit -m 'Auto Update'
          echo "${{ secrets.AUR_SSHKEY }}" > .ssh_key
          chown runner .ssh_key
          chmod 600 .ssh_key
          GIT_SSH_COMMAND="ssh -i ./.ssh_key -o StrictHostKeyChecking=no" git push
