---

name: Nightly Build

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '40 14 * * *'
jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Depends
        run: sudo apt install pkg-config libglib2.0-dev -y

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build with Meson
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: 'build'
          directory: '_setup'
          setup-options: '--prefix=~/_libee_nightly_build'
          meson-version: '1.3.0'
          ninja-version: '1.9.0.post1'

      - name: Copy files
        run: cd _setup && sudo ninja install

      - name: Setup P7zip
        run: sudo apt install p7zip-full -y

      - name: Config Date
        run: echo "_NIGHTLY_TS=$(date +"%Y_%m_%d_%I_%M_%S_%p")" >> $GITHUB_ENV

      - name: Archive Artifact
        run: 7z a -scrc=SHA1 -sdel -mmt2 -mx4 ~/libeventemitter_nightly_${_NIGHTLY_TS}.7z ~/_libee_nightly_build

      - name: Create New Release of Nightly Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create nightly_${_NIGHTLY_TS} \
            --title "Nightly Release: ${_NIGHTLY_TS}" \
            --notes "Nightly Release" \
            ~/libeventemitter_nightly_${_NIGHTLY_TS}.7z
