---

name: Format Source

on:  # yamllint disable-line rule:truthy
  push

jobs:
  formatsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clang-Format
        run: sudo apt install clang-format -y

      - name: Format Source
        run: cd maintenance && sh format.sh && cd ..

      - name: Push Source
        run: |
          git config --global user.name "Twinkle[bot]"
          git config --global user.email "example@example.com"

          git add .

          git commit -m "+Action: Maintenance+ format sources" || true

          git push || true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
